@startuml
StreamSpawner --* RaindropStreamPool 

RaindropStreamPool --* UnoccupiedColumnPool
RaindropStreamPool --* StandardRaindropFactory

UnoccupiedColumnPool --* IColumnNumberPicker
IColumnNumberPicker <|-- RoundRobinColumnNumberPicker
IColumnNumberPicker <|-- RandomColumnNumberPicker

RaindropStreamPool : +RaindropStream Create()
RaindropStreamPool : +void Restore(Set<RaindropStream> streams)
RaindropStreamPool : +bool IsLow() {get}

UnoccupiedColumnPool : +Column PickOne()
UnoccupiedColumnPool : +void Restore(Set<Column>)
UnoccupiedColumnPool : +int ColumnCount() {get}
UnoccupiedColumnPool : +bool IsLow() {get}

interface IColumnNumberPicker
IColumnNumberPicker : +int PickOne()
IColumnNumberPicker : +void RestoreOne(int columnNumber)
IColumnNumberPicker : +int ColumnCount() {get}
IColumnNumberPicker : +bool IsLow() {get}

StandardRaindropFactory : +StandardRaindrop Create()
@enduml
