@startuml
StreamSpawner --* RaindropStreamPool 

RaindropStreamPool --* UnoccupiedColumnPool
RaindropStreamPool --* StandardRaindropFactory

UnoccupiedColumnPool --* IColumnNumberPicker
IColumnNumberPicker <|-- RoundRobinColumnNumberPicker
IColumnNumberPicker <|-- RandomColumnNumberPicker
@enduml
